theme = "theme0"


[editor]
cursorline=true
line-number="relative"
bufferline="always"
color-modes=true


[editor.cursor-shape]
insert = "block"

[editor.soft-wrap]
enable=true


[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
